--CRIANDO TABELA PARA AS CATEGORIAS
CREATE TABLE PUBLIC.TBCATEGORIA (
    CATEGORIAID INTEGER,
    CATEGORIA VARCHAR(100) NOT NULL,
    DEPARTAMENTO VARCHAR(50),
    DESCRICAO VARCHAR(200),
  PRIMARY KEY (CATEGORIAID)
)

--CRIANDO TABELA PARA FORNECEDORES
CREATE TABLE PUBLIC.TBFORNECEDOR (
	FORNECEDORID INTEGER,
	FORNECEDOR VARCHAR(100) NOT NULL,
	FORNECEDORCONTATO VARCHAR(100),
	FORNECEDORPAIS VARCHAR(30),
  PRIMARY KEY (FORNECEDORID)
)

--CRIANDO TABELA PARA PRODUTOS
CREATE TABLE PUBLIC.TBPRODUTO (
   PRODUTOID INTEGER,
   CATEGORIAID INTEGER NOT NULL,
   PRODUTO VARCHAR(150),
   FORNECEDORID INTEGER NOT NULL,
  PRIMARY KEY(PRODUTOID),
  FOREIGN KEY (CATEGORIAID) REFERENCES PUBLIC.TBCATEGORIA(CATEGORIAID),
  FOREIGN KEY (FORNECEDORID) REFERENCES PUBLIC.TBFORNECEDOR(FORNECEDORID)
)

--CRIANDO TABELA PARA ESCRITORIOS
CREATE TABLE PUBLIC.TBESCRITORIO (
  ESCRITORIOS INTEGER,
  ESCRITORIOLOCALIZACAO VARCHAR(100) NOT NULL,
 PRIMARY KEY(ESCRITORIOS)
)

--CRIANDO TABELA PARA FUNCIONARIOS
CREATE TABLE PUBLIC.TBFUNCIONARIO ( 
  FUNCIONARIOID INTEGER,
  EXTENSAO INTEGER,
  NOMEFUNCIONARIO VARCHAR(100) NOT NULL,
  GENERO VARCHAR(1) NOT NULL,
  DATAADMISSAO DATE NOT NULL,
  ESCRITORIO SMALLINT NOT NULL,
  SUPERVISOR VARCHAR(100),
  CARGO VARCHAR(100),
  SALARIOANUAL INTEGER,
  METAVENDAS INTEGER,
 PRIMARY KEY(FUNCIONARIOID),
 FOREIGN KEY (ESCRITORIO) REFERENCES PUBLIC.TBESCRITORIO(ESCRITORIOS) 
)

--CRIANDO TABELA PARA ARMAZENAR AS VENDAS
CREATE TABLE PUBLIC.TBVENDA (
	CUPOMID INTEGER,
	PRODUTOID INTEGER NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	VALOR NUMERIC(10, 4) NOT NULL,
	DESCONTO NUMERIC(10, 4),
	CUSTO NUMERIC(10, 4) NOT NULL,
	VALORLIQUIDO NUMERIC(10,4) NOT NULL,
  PRIMARY KEY (CUPOMID, PRODUTOID),
  FOREIGN KEY (PRODUTOID) REFERENCES TBPRODUTO(PRODUTOID),
  FOREIGN KEY (CUPOMID) REFERENCES TBFRETE(CUPOMID)
)

--CRIANDO TABELA PARA ARMAZENAR OS CLIENTES
CREATE TABLE PUBLIC.TBCLIENTE (
	CLIENTEID INTEGER,
	CLIENTE VARCHAR(100) NOT NULL,
	NOMECONTATO VARCHAR(100),
	ENDERECO TEXT ,
	CIDADE VARCHAR(100),
	PAIS VARCHAR(50),
	PAISCODIGO VARCHAR(2),
	REGIAO VARCHAR(30),
	CEP VARCHAR(8),
	LATITUDE DOUBLE PRECISION,
	LONGITUDE DOUBLE PRECISION,
	FAX VARCHAR(20),
	TELEFONE VARCHAR(20),
   PRIMARY KEY (CLIENTEID)
)

--CRIANDO TABELA PARA ARMAZENAR OS FRETES
CREATE TABLE PUBLIC.TBFRETE (
	DATA DATE,
	CLIENTEID INTEGER NOT NULL,
	FUNCIONARIOID INTEGER NOT NULL,
    VALORFRETE NUMERIC(10, 4) NOT NULL,
	CUPOMID INTEGER NOT NULL,
	EMPRESAFRETE VARCHAR(100),
	DATAENTREGA DATE,
   PRIMARY KEY (CUPOMID),
   FOREIGN KEY (CLIENTEID) REFERENCES PUBLIC.TBCLIENTE(CLIENTEID),
   FOREIGN KEY (FUNCIONARIOID) REFERENCES PUBLIC.TBFUNCIONARIO(FUNCIONARIOID)
)

