--VALOR TOTAL DAS VENDAS E DOS FRETES POR PRODUTO;
SELECT PRODUTO AS PRODUTO_CODIGO,
       SUM(VALOR) AS VALOR_TOTAL_VENDA,
       SUM(VALORFRETE) AS VALOR_TOTAL_FRETE
 FROM TBVENDA VEN 
 JOIN TBFRETE FRE
  ON FRE.CUPOMID = VEN.CUPOMID
 JOIN TBPRODUTO PRO
  ON PRO.PRODUTOID = VEN.PRODUTOID
  GROUP BY PRO.PRODUTOID 
  ORDER BY PRO.PRODUTOID
  
--VALOR TOTAL DAS VENDAS E DOS FRETES POR ORDEM DE VENDA;
  SELECT 
       VEN.CUPOMID,
       SUM(VALOR) AS VALOR_TOTAL_VENDA,
       SUM(VALORFRETE) AS VALOR_TOTAL_FRETE
 FROM TBVENDA VEN 
 JOIN TBFRETE FRE
  ON FRE.CUPOMID = VEN.CUPOMID
  GROUP BY VEN.CUPOMID
  ORDER BY VEN.CUPOMID
  
--VALOR DE VENDA POR TIPO DE PRODUTO
SELECT CAT.CATEGORIA AS NOME_CATEGORIA,
       SUM(VEN.VALOR) AS VALOR_TOTAL_VENDA    
  FROM TBVENDA VEN
  JOIN TBPRODUTO PRO 
   ON PRO.PRODUTOID = VEN.PRODUTOID
  JOIN TBCATEGORIA CAT
   ON CAT.CATEGORIAID = PRO.CATEGORIAID
  GROUP BY CAT.CATEGORIAID
  ORDER BY CAT.CATEGORIAID
 
--QUANTIDADE E VALOR DAS VENDAS POR DIA;
 SELECT TO_CHAR(DATA, 'DD MON YYYY') AS DATA_AJUSTADA,
 	    SUM(QUANTIDADE) AS QUANTIDADE_TOTAL_VENDAS,
        SUM(VALOR) AS VALOR_TOTAL_VENDAS     
   FROM TBVENDA VEN
   JOIN TBFRETE FRE
    ON FRE.CUPOMID = VEN.CUPOMID
   GROUP BY DATA
   ORDER BY DATA

--QUANTIDADE E VALOR DAS VENDAS POR MÊS;
SELECT MES,
       SUM(QUANTIDADE) AS QUANTIDADE_TOTAL_VENDAS,
       SUM(VALOR) AS VALOR_TOTAL_VENDAS
  FROM (
		SELECT TO_CHAR(DATA, 'MON') AS MES,
		 	    QUANTIDADE,
		        VALOR
		   FROM TBVENDA VEN
		   JOIN TBFRETE FRE
		    ON FRE.CUPOMID = VEN.CUPOMID 
	   ) MES
   GROUP BY MES
   ORDER BY MES
  
   
--QUANTIDADE E VALOR DAS VENDAS POR ANO;
SELECT ANO,
       SUM(QUANTIDADE) AS QUANTIDADE_TOTAL_VENDAS,
       SUM(VALOR) AS VALOR_TOTAL_VENDAS 
  FROM (
		SELECT TO_CHAR(DATA, 'YYYY') AS ANO,
		 	    QUANTIDADE,
		        VALOR    
		   FROM TBVENDA VEN
		   JOIN TBFRETE FRE
		    ON FRE.CUPOMID = VEN.CUPOMID
	   ) ANO
   GROUP BY ANO
   ORDER BY ANO
   
--LUCRO DOS MESES
SELECT MES_E_ANO,
       SUM(LUCRO)
  FROM (
		 SELECT TO_CHAR(DATA, 'MM YYYY') AS MES_E_ANO,
		        VALORLIQUIDO AS LUCRO
		   FROM TBVENDA VEN
		   JOIN TBFRETE FRE
		    ON FRE.CUPOMID = VEN.CUPOMID
	   ) DAT_FORMAT
   GROUP BY MES_E_ANO
   ORDER BY MES_E_ANO
   
--VENDA POR PRODUTO
SELECT PRO.PRODUTO AS PRODUTO,
	   COUNT(*) AS NUMERO_DE_VENDAS,
       SUM(QUANTIDADE) AS QUANTIDADE_TOTAL_PRODUTOS_VENDIDOS,
       SUM(VALOR) AS VALOR_TOTAL,
       SUM(VALORLIQUIDO) AS LUCRO_TOTAL
  FROM TBVENDA VEN
  JOIN TBPRODUTO PRO 
   ON VEN.PRODUTOID = PRO.PRODUTOID
  GROUP BY PRO.PRODUTOID
  ORDER BY PRODUTO
  
--VENDA POR CLIENTE
SELECT CLIENTE,
       COUNT(*) AS NUMERO_DE_VENDAS,
       SUM(VALOR) AS VALOR_TOTAL,
       SUM(VALORLIQUIDO) AS LUCRO_TOTAL
  FROM TBVENDA VEN
  JOIN TBFRETE FRE
   ON FRE.CUPOMID = VEN.CUPOMID
  JOIN TBCLIENTE CLI
   ON CLI.CLIENTEID = FRE.CLIENTEID
  GROUP BY CLI.CLIENTEID
  ORDER BY CLIENTE
  
--VENDA POR CIDADE DO CLIENTE
 SELECT CIDADE,
       COUNT(*) AS NUMERO_DE_VENDAS,
       SUM(VALOR) AS VALOR_TOTAL,
       SUM(VALORLIQUIDO) AS LUCRO_TOTAL
  FROM TBVENDA VEN
  JOIN TBFRETE FRE
   ON FRE.CUPOMID = VEN.CUPOMID
  JOIN TBCLIENTE CLI
   ON CLI.CLIENTEID = FRE.CLIENTEID
  GROUP BY CLI.CIDADE
  ORDER BY CIDADE
  
--VENDA POR ESTADO DO CLIENTE (O CSV CLIENTES NAO POSSUI A COLUNA ESTADO, FEITO POR PAIS COMO SUBSTITUIÇÃO)
   SELECT PAIS,
       COUNT(*) AS NUMERO_DE_VENDAS,
       SUM(VALOR) AS VALOR_TOTAL,
       SUM(VALORLIQUIDO) AS LUCRO_TOTAL
  FROM TBVENDA VEN
  JOIN TBFRETE FRE
   ON FRE.CUPOMID = VEN.CUPOMID
  JOIN TBCLIENTE CLI
   ON CLI.CLIENTEID = FRE.CLIENTEID
  GROUP BY CLI.PAIS
  ORDER BY PAIS
  
--MÉDIA DE PRODUTOS VENDIDOS GERAL
  SELECT AVG(QUANTIDADE) AS MEDIA_QUANTIDADE_POR_VENDA
   FROM TBVENDA VEN
   JOIN TBPRODUTO PRO
    ON PRO.PRODUTOID = VEN.PRODUTOID

--COMPLEMENTO MÉDIA DE PRODUTOS VENDIDOS, SEPARANDO POR PRODUTO, OU SEJA, A MÉDIA DE PRODUTOS VENDIDOS EM CADA VENDA SEPARADO POR PRODUTO.
 SELECT PRODUTO,
        AVG(QUANTIDADE) AS MEDIA_QUANTIDADE_POR_VENDA
   FROM TBVENDA VEN
   JOIN TBPRODUTO PRO
    ON PRO.PRODUTOID = VEN.PRODUTOID
   GROUP BY PRO.PRODUTOID
   ORDER BY PRODUTO

--MÉDIA DE COMPRAS QUE UM CLIENTE FAZ.
SELECT CLIENTE,
       AVG(QUANTIDADE) AS MEDIA_QUANTIDADE_POR_COMPRA
  FROM TBVENDA VEN
  JOIN TBFRETE FRE
   ON FRE.CUPOMID = VEN.CUPOMID
  JOIN TBCLIENTE CLI
   ON FRE.CLIENTEID = CLI.CLIENTEID
  GROUP BY CLI.CLIENTEID
  ORDER BY CLIENTE